app:
  zenoh_prefix: "wakeword"
  system_prompts:
    "Hey Hopper": "You are a hexapod pet robot called Hopper. You can high five, fold, stand up, sit down. You can also do dance. Or change your face to an animation of the larson scanner."
    "Hopper Stop": "You are a hexapod pet robot called Hopper. You can high five, fold, stand up, sit down. You can also do dance. Or change your face to an animation of the larson scanner."
    "Wintermute": "You are a hexapod pet robot called Hopper. You can high five, fold, stand up, sit down. You can also do dance. Or change your face to an animation of the larson scanner."
    "bumblebee": "You are a hexapod pet robot called Hopper. You can high five, fold, stand up, sit down. You can also do dance. Or change your face to an animation of the larson scanner."
  enable_respeaker_integration: true
picovoice:
  access_key: "ACCESS_KEY"
  audio_device_index: -1
  keyword_paths:
    "Hey Hopper": "/var/lib/wakeword/keyword_files/Hey-Hopper_en_raspberry-pi_v3_0_0.ppn"
    "Hopper Stop": "/var/lib/wakeword/keyword_files/Hopper-Stop_en_raspberry-pi_v3_0_0.ppn"
    "bumblebee": "/var/lib/wakeword/default_keyword_files/bumblebee_raspberry-pi.ppn"
    "Wintermute": "/var/lib/wakeword/keyword_files/Wintermute_en_raspberry-pi_v3_0_0.ppn"
    "dismiss": "/var/lib/wakeword/keyword_files/Dismiss_en_raspberry-pi_v3_0_0.ppn"
  dismiss_keyword: "dismiss"
  sensitivities:
    - 0.2
    - 0.2
    - 0.2
    - 0.5
    - 0.3
  # Default keywords aren't portable
  # keywords:
  #  - "bumblebee"
  # These libraries aren't very portable so copying them here fixes that
  cobra_lib_path: /var/lib/wakeword/libpv_cobra.so
  porcupine_lib_path: /var/lib/wakeword/libpv_porcupine.so
  recorder_lib_path: /var/lib/wakeword/libpv_recorder.so
  model_path: /var/lib/wakeword/porcupine_params.pv
openai:
  api_key: "API_KEY"
zenoh:
  connect:
    - "tcp/SOME_IP:7447"
  listen:
    - "tcp/0.0.0.0:7447"
    - "udp/0.0.0.0:7448"
