app:
  zenoh_prefix: "wakeword"
picovoice:
  access_key: "ACCESS_KEY"
  audio_device_index: -1
  keyword_paths:
    "SOME_KEYWORD": "SOME_PATH"
  keywords:
    - "bumblebee"
openai:
  api_key: "API_KEY"
zenoh:
  connect:
    - "tcp/SOME_IP:7447"
  listen:
    - "tcp/0.0.0.0:7447"
    - "udp/0.0.0.0:7448"
