app:
  zenoh_prefix: "wakeword"
  system_prompts:
    "Hey Hopper": "You are a hexapod pet robot called Hopper. You can high five, fold, stand up, sit down. You can also do dance. Or change your face to an animation of the larson scanner."
    "Hopper Stop": "You are a hexapod pet robot called Hopper. You can high five, fold, stand up, sit down. You can also do dance. Or change your face to an animation of the larson scanner."
    "bumblebee": "You are a hexapod pet robot called Hopper. You can high five, fold, stand up, sit down. You can also do dance. Or change your face to an animation of the larson scanner."
    "Wintermute": "You are a hexapod pet robot called Hopper. You can high five, fold, stand up, sit down. You can also do dance. Or change your face to an animation of the larson scanner."
    "Songbird": "You are a hexapod pet robot called Hopper. You can high five, fold, stand up, sit down. You can also do dance. Or change your face to an animation of the larson scanner."
  enable_respeaker_integration: true
picovoice:
  access_key: "ACCESS_KEY"
  audio_device_index: -1
  keyword_paths:
    "Hey Hopper": "keywords/Hey-Hopper_en_raspberry-pi_v3_0_0.ppn"
    "Hopper Stop": "keywords/Hopper-Stop_en_raspberry-pi_v3_0_0.ppn"
    "dismiss": "keywords/Dismiss_en_raspberry-pi_v3_0_0.ppn"
    "Wintermute": "keywords/Wintermute_en_raspberry-pi_v3_0_0.ppn"
    "Songbird": "/var/lib/wakeword/keyword_files/Songbird_en_raspberry-pi_v3_0_0.ppn"
  keywords:
    - "bumblebee"
  dismiss_keyword: "dismiss"
openai:
  api_key: "API_KEY"
zenoh:
  connect:
    - "tcp/SOME_IP:7447"
  listen:
    - "tcp/0.0.0.0:7447"
    - "udp/0.0.0.0:7448"
